/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRendezVousRouteImport } from './routes/_authenticated/rendez-vous'
import { Route as AuthenticatedPreferencesRouteImport } from './routes/_authenticated/preferences'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDossiersIndexRouteImport } from './routes/_authenticated/dossiers.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedDossiersIdRouteImport } from './routes/_authenticated/dossiers.$id'
import { Route as AuthenticatedAdminSecurityRouteImport } from './routes/_authenticated/admin.security'
import { Route as AuthenticatedAdminRendezVousRouteImport } from './routes/_authenticated/admin.rendez-vous'
import { Route as AuthenticatedAdminDossiersRouteImport } from './routes/_authenticated/admin.dossiers'
import { Route as AuthenticatedAdminDirectionRouteImport } from './routes/_authenticated/admin.direction'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin.audit'
import { Route as AuthenticatedAdminMessagesIndexRouteImport } from './routes/_authenticated/admin.messages.index'
import { Route as AuthenticatedAdminClientsIndexRouteImport } from './routes/_authenticated/admin.clients.index'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as AuthenticatedAdminMessagesClientIdRouteImport } from './routes/_authenticated/admin.messages.$clientId'
import { Route as AuthenticatedAdminClientsIdRouteImport } from './routes/_authenticated/admin.clients.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRendezVousRoute = AuthenticatedRendezVousRouteImport.update({
  id: '/rendez-vous',
  path: '/rendez-vous',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPreferencesRoute =
  AuthenticatedPreferencesRouteImport.update({
    id: '/preferences',
    path: '/preferences',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDossiersIndexRoute =
  AuthenticatedDossiersIndexRouteImport.update({
    id: '/dossiers/',
    path: '/dossiers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDossiersIdRoute = AuthenticatedDossiersIdRouteImport.update({
  id: '/dossiers/$id',
  path: '/dossiers/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminSecurityRoute =
  AuthenticatedAdminSecurityRouteImport.update({
    id: '/admin/security',
    path: '/admin/security',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRendezVousRoute =
  AuthenticatedAdminRendezVousRouteImport.update({
    id: '/admin/rendez-vous',
    path: '/admin/rendez-vous',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminDossiersRoute =
  AuthenticatedAdminDossiersRouteImport.update({
    id: '/admin/dossiers',
    path: '/admin/dossiers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminDirectionRoute =
  AuthenticatedAdminDirectionRouteImport.update({
    id: '/admin/direction',
    path: '/admin/direction',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminMessagesIndexRoute =
  AuthenticatedAdminMessagesIndexRouteImport.update({
    id: '/admin/messages/',
    path: '/admin/messages/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminClientsIndexRoute =
  AuthenticatedAdminClientsIndexRouteImport.update({
    id: '/admin/clients/',
    path: '/admin/clients/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminMessagesClientIdRoute =
  AuthenticatedAdminMessagesClientIdRouteImport.update({
    id: '/admin/messages/$clientId',
    path: '/admin/messages/$clientId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminClientsIdRoute =
  AuthenticatedAdminClientsIdRouteImport.update({
    id: '/admin/clients/$id',
    path: '/admin/clients/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/preferences': typeof AuthenticatedPreferencesRoute
  '/rendez-vous': typeof AuthenticatedRendezVousRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/direction': typeof AuthenticatedAdminDirectionRoute
  '/admin/dossiers': typeof AuthenticatedAdminDossiersRoute
  '/admin/rendez-vous': typeof AuthenticatedAdminRendezVousRoute
  '/admin/security': typeof AuthenticatedAdminSecurityRoute
  '/dossiers/$id': typeof AuthenticatedDossiersIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/dossiers/': typeof AuthenticatedDossiersIndexRoute
  '/admin/clients/$id': typeof AuthenticatedAdminClientsIdRoute
  '/admin/messages/$clientId': typeof AuthenticatedAdminMessagesClientIdRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/admin/clients/': typeof AuthenticatedAdminClientsIndexRoute
  '/admin/messages/': typeof AuthenticatedAdminMessagesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/preferences': typeof AuthenticatedPreferencesRoute
  '/rendez-vous': typeof AuthenticatedRendezVousRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/direction': typeof AuthenticatedAdminDirectionRoute
  '/admin/dossiers': typeof AuthenticatedAdminDossiersRoute
  '/admin/rendez-vous': typeof AuthenticatedAdminRendezVousRoute
  '/admin/security': typeof AuthenticatedAdminSecurityRoute
  '/dossiers/$id': typeof AuthenticatedDossiersIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/dossiers': typeof AuthenticatedDossiersIndexRoute
  '/admin/clients/$id': typeof AuthenticatedAdminClientsIdRoute
  '/admin/messages/$clientId': typeof AuthenticatedAdminMessagesClientIdRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/admin/clients': typeof AuthenticatedAdminClientsIndexRoute
  '/admin/messages': typeof AuthenticatedAdminMessagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/preferences': typeof AuthenticatedPreferencesRoute
  '/_authenticated/rendez-vous': typeof AuthenticatedRendezVousRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/direction': typeof AuthenticatedAdminDirectionRoute
  '/_authenticated/admin/dossiers': typeof AuthenticatedAdminDossiersRoute
  '/_authenticated/admin/rendez-vous': typeof AuthenticatedAdminRendezVousRoute
  '/_authenticated/admin/security': typeof AuthenticatedAdminSecurityRoute
  '/_authenticated/dossiers/$id': typeof AuthenticatedDossiersIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/dossiers/': typeof AuthenticatedDossiersIndexRoute
  '/_authenticated/admin/clients/$id': typeof AuthenticatedAdminClientsIdRoute
  '/_authenticated/admin/messages/$clientId': typeof AuthenticatedAdminMessagesClientIdRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/_authenticated/admin/clients/': typeof AuthenticatedAdminClientsIndexRoute
  '/_authenticated/admin/messages/': typeof AuthenticatedAdminMessagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/dashboard'
    | '/messages'
    | '/notifications'
    | '/preferences'
    | '/rendez-vous'
    | '/admin/audit'
    | '/admin/direction'
    | '/admin/dossiers'
    | '/admin/rendez-vous'
    | '/admin/security'
    | '/dossiers/$id'
    | '/admin/'
    | '/dossiers/'
    | '/admin/clients/$id'
    | '/admin/messages/$clientId'
    | '/lovable/email/queue/process'
    | '/admin/clients/'
    | '/admin/messages/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/dashboard'
    | '/messages'
    | '/notifications'
    | '/preferences'
    | '/rendez-vous'
    | '/admin/audit'
    | '/admin/direction'
    | '/admin/dossiers'
    | '/admin/rendez-vous'
    | '/admin/security'
    | '/dossiers/$id'
    | '/admin'
    | '/dossiers'
    | '/admin/clients/$id'
    | '/admin/messages/$clientId'
    | '/lovable/email/queue/process'
    | '/admin/clients'
    | '/admin/messages'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/dashboard'
    | '/_authenticated/messages'
    | '/_authenticated/notifications'
    | '/_authenticated/preferences'
    | '/_authenticated/rendez-vous'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/direction'
    | '/_authenticated/admin/dossiers'
    | '/_authenticated/admin/rendez-vous'
    | '/_authenticated/admin/security'
    | '/_authenticated/dossiers/$id'
    | '/_authenticated/admin/'
    | '/_authenticated/dossiers/'
    | '/_authenticated/admin/clients/$id'
    | '/_authenticated/admin/messages/$clientId'
    | '/lovable/email/queue/process'
    | '/_authenticated/admin/clients/'
    | '/_authenticated/admin/messages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/rendez-vous': {
      id: '/_authenticated/rendez-vous'
      path: '/rendez-vous'
      fullPath: '/rendez-vous'
      preLoaderRoute: typeof AuthenticatedRendezVousRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/preferences': {
      id: '/_authenticated/preferences'
      path: '/preferences'
      fullPath: '/preferences'
      preLoaderRoute: typeof AuthenticatedPreferencesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dossiers/': {
      id: '/_authenticated/dossiers/'
      path: '/dossiers'
      fullPath: '/dossiers/'
      preLoaderRoute: typeof AuthenticatedDossiersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dossiers/$id': {
      id: '/_authenticated/dossiers/$id'
      path: '/dossiers/$id'
      fullPath: '/dossiers/$id'
      preLoaderRoute: typeof AuthenticatedDossiersIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/security': {
      id: '/_authenticated/admin/security'
      path: '/admin/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AuthenticatedAdminSecurityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/rendez-vous': {
      id: '/_authenticated/admin/rendez-vous'
      path: '/admin/rendez-vous'
      fullPath: '/admin/rendez-vous'
      preLoaderRoute: typeof AuthenticatedAdminRendezVousRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/dossiers': {
      id: '/_authenticated/admin/dossiers'
      path: '/admin/dossiers'
      fullPath: '/admin/dossiers'
      preLoaderRoute: typeof AuthenticatedAdminDossiersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/direction': {
      id: '/_authenticated/admin/direction'
      path: '/admin/direction'
      fullPath: '/admin/direction'
      preLoaderRoute: typeof AuthenticatedAdminDirectionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/messages/': {
      id: '/_authenticated/admin/messages/'
      path: '/admin/messages'
      fullPath: '/admin/messages/'
      preLoaderRoute: typeof AuthenticatedAdminMessagesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/clients/': {
      id: '/_authenticated/admin/clients/'
      path: '/admin/clients'
      fullPath: '/admin/clients/'
      preLoaderRoute: typeof AuthenticatedAdminClientsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/messages/$clientId': {
      id: '/_authenticated/admin/messages/$clientId'
      path: '/admin/messages/$clientId'
      fullPath: '/admin/messages/$clientId'
      preLoaderRoute: typeof AuthenticatedAdminMessagesClientIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/clients/$id': {
      id: '/_authenticated/admin/clients/$id'
      path: '/admin/clients/$id'
      fullPath: '/admin/clients/$id'
      preLoaderRoute: typeof AuthenticatedAdminClientsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedPreferencesRoute: typeof AuthenticatedPreferencesRoute
  AuthenticatedRendezVousRoute: typeof AuthenticatedRendezVousRoute
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminDirectionRoute: typeof AuthenticatedAdminDirectionRoute
  AuthenticatedAdminDossiersRoute: typeof AuthenticatedAdminDossiersRoute
  AuthenticatedAdminRendezVousRoute: typeof AuthenticatedAdminRendezVousRoute
  AuthenticatedAdminSecurityRoute: typeof AuthenticatedAdminSecurityRoute
  AuthenticatedDossiersIdRoute: typeof AuthenticatedDossiersIdRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedDossiersIndexRoute: typeof AuthenticatedDossiersIndexRoute
  AuthenticatedAdminClientsIdRoute: typeof AuthenticatedAdminClientsIdRoute
  AuthenticatedAdminMessagesClientIdRoute: typeof AuthenticatedAdminMessagesClientIdRoute
  AuthenticatedAdminClientsIndexRoute: typeof AuthenticatedAdminClientsIndexRoute
  AuthenticatedAdminMessagesIndexRoute: typeof AuthenticatedAdminMessagesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedPreferencesRoute: AuthenticatedPreferencesRoute,
  AuthenticatedRendezVousRoute: AuthenticatedRendezVousRoute,
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminDirectionRoute: AuthenticatedAdminDirectionRoute,
  AuthenticatedAdminDossiersRoute: AuthenticatedAdminDossiersRoute,
  AuthenticatedAdminRendezVousRoute: AuthenticatedAdminRendezVousRoute,
  AuthenticatedAdminSecurityRoute: AuthenticatedAdminSecurityRoute,
  AuthenticatedDossiersIdRoute: AuthenticatedDossiersIdRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedDossiersIndexRoute: AuthenticatedDossiersIndexRoute,
  AuthenticatedAdminClientsIdRoute: AuthenticatedAdminClientsIdRoute,
  AuthenticatedAdminMessagesClientIdRoute:
    AuthenticatedAdminMessagesClientIdRoute,
  AuthenticatedAdminClientsIndexRoute: AuthenticatedAdminClientsIndexRoute,
  AuthenticatedAdminMessagesIndexRoute: AuthenticatedAdminMessagesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
